# Generated by Django 3.0.3 on 2020-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200711_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription_course',
            name='parent_course',
        ),
        migrations.RemoveField(
            model_name='subscription_course',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='subscription_plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ImageField(default='media/course_pictures/cover1.jpg', upload_to='course_pictures'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='school',
        ),
        migrations.DeleteModel(
            name='subscription_course',
        ),
        migrations.DeleteModel(
            name='subscription_plan',
        ),
    ]
