# Generated by Django 3.0.3 on 2020-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_course_course_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='intern_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=15)),
                ('queries', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=15)),
                ('queries', models.CharField(max_length=100)),
            ],
        ),
    ]
